### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by Err0r1** [FusionGen/FusionGEN#116]
- [x] Update CI3 to the latest version 

- [x] Full PHP 8 compatibility

- [x] Update TinyMCE

- [x] Update Smarty

- [x] Update PayPal Api

- [x] ACP in bootstrap design

- [ ] Session DB Handling

- [x] CMangos compatibility

- [x] Merge PW recovery to one module and compatibility to SHP/SRP6/HEX

- [x] Account activation (email)

**Comment by Dokman** [comment]
is pushed the latest php compatibility?

**Comment by Err0r1** [comment]
It's progressing
Currently working on the new default theme

Join discord for further infos

Everyone I've asked who could help doesn't have time or didn't respond
So it will take a long time
